# Generated by Django 4.2.2 on 2023-07-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('number', models.PositiveSmallIntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('complement', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
