# Generated by Django 4.2.2 on 2023-07-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_seller_productorder_productcart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='carts',
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
